Feature/twitter text cleaner
lakshya1730/Movie-Reviews pull request #2
Opened 2020-12-19 14:55 UTC by lakshya1730

this code takes the tweet data and cleans it to give a clean tweet along with removing the stopwords

2020-12-23 01:05 UTC, jediXNavi requested changes

2020-12-23 01:05 UTC, jediXNavi commented on Tweet Cleaner/Twitter_Text_Cleaner.ipynb
> +        "    soup = BeautifulSoup(text, 'lxml')\r\n",
Why do we need BeautifulSoup to parse the text? that's anyway stored in a text column na! Why do we parse it to an xml format? Why can't we read directly and do pd.apply?

2020-12-23 01:05 UTC, jediXNavi commented on Tweet Cleaner/Twitter_Text_Cleaner.ipynb
> +        "test_result = []\r\n",
I think let's not have a list here. If the data we want( talking from a production standpoint) is in millions, the list would be infeasible. Instead let's directly apply a pandas function! For now, that should be fine. Incase we need better processing can switch over to some Big data framework.

2020-12-23 01:05 UTC, jediXNavi commented on Tweet Cleaner/Twitter_Text_Cleaner.ipynb
> +        "    stpword = stopwords.words('english')\r\n",
For every tweet text, it will get the list of stopwords. Better to have it as a global variable

2020-12-23 07:35 UTC, lakshya1730 commented on Tweet Cleaner/Twitter_Text_Cleaner.ipynb
> +        "    soup = BeautifulSoup(text, 'lxml')\r\n",
@jediXNavi  would pd.apply be able to identify any text that has lxml properties??

2020-12-23 07:36 UTC, lakshya1730 commented on Tweet Cleaner/Twitter_Text_Cleaner.ipynb
> +        "    stpword = stopwords.words('english')\r\n",
@jediXNavi makes complete sense will update this bit and recommit the code

2021-02-19 07:57 UTC, jediXNavi approved these changes

2021-02-19 07:57 UTC, merged